/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Run
         * @description Delete a run and all of its events/iters/descendants.
         *
         *     DB-only — does NOT touch files on disk (worktree, run_dir);
         *     mirrors ``DELETE /api/projects/{id}``. Reclaiming on-disk space is a
         *     separate manual ``rm -rf .relay/runs/<id>`` step.
         *
         *     ``404`` if ``run_id`` is unknown. ``409`` if the run is currently
         *     active (``running``/``awaiting_children``) — cancel it first.
         */
        delete: operations["delete_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Run Children
         * @description Direct children of a run (spec.md §7, 9e).
         *
         *     Returns the rows where ``parent_run_id == run_id``, ordered by
         *     ``started_at`` ascending. Returns ``[]`` for a parent that never
         *     fanned out. 404 if ``run_id`` itself is unknown.
         */
        get: operations["list_run_children_api_runs__run_id__children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Run Events */
        get: operations["list_run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Run
         * @description Pure render — no run row/dir/event is created (W1 contract).
         *
         *     ``run_id`` here is the *project id* the caller wants to preview a
         *     run for (spec.md §7 nests preview under runs but it operates on a
         *     project + a prospective prompt). Non-int path segment → 400.
         */
        get: operations["preview_run_api_runs__run_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Unregister a project and cascade-delete its runs + prompts.
         *     DB-only; never touches files on disk. 404 unknown project; 409 if
         *     any run is currently active (cancel first).
         */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompts */
        get: operations["list_prompts_api_prompts_get"];
        put?: never;
        /** Create Prompt */
        post: operations["create_prompt_api_prompts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{prompt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prompt */
        get: operations["get_prompt_api_prompts__prompt_id__get"];
        /** Update Prompt */
        put: operations["update_prompt_api_prompts__prompt_id__put"];
        post?: never;
        /** Delete Prompt */
        delete: operations["delete_prompt_api_prompts__prompt_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{prompt_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompt Versions */
        get: operations["list_prompt_versions_api_prompts__prompt_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Files
         * @description Project-root directory listing (thin adapter over
         *     :func:`serve_listing`; sandbox root = the project's ``root_path``).
         */
        get: operations["list_files_api_projects__project_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/files/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Project-root file content (thin adapter over :func:`serve_file`;
         *     sandbox root = the project's ``root_path``).
         */
        get: operations["get_file_api_projects__project_id__files__file_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description SSE live stream / replay for a run (spec.md §7, ADR-23).
         */
        get: operations["stream_events_api_events__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description Directory listing of the run's artifacts dir (thin adapter over
         *     the shared :func:`~relay.api.files.serve_listing`).
         */
        get: operations["list_artifacts_api_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/artifacts/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Text content of one artifact file (thin adapter over the shared
         *     :func:`~relay.api.files.serve_file`; binary → 415, >5 MiB →
         *     413).
         */
        get: operations["get_artifact_api_runs__run_id__artifacts__file_path__get"];
        /**
         * Put Artifact
         * @description Write text content to a sandboxed artifact during a paused review
         *     (spec §6.2, §7; ADR-40). Thin adapter over
         *     :meth:`relay.core.RelayCore.write_artifact`.
         *
         *     Body: ``{"content": str, "editor"?: str}``. The endpoint is the
         *     **single write entry point** on the run artifacts dir; it requires
         *     the run to be ``paused`` AND the requested path to be a member of
         *     the latest paused iter's ``signal_args.review_paths`` (set by 14b,
         *     plural per 14f / ADR-41; a paused iter from 14a–14d that carries
         *     only the legacy scalar ``review_path`` is read as a one-element
         *     list for migration). On success the event store gains one
         *     ``artifact_edited`` event with the pre/post SHA-256 hashes and
         *     sizes — the audit trail per ADR-10.
         *
         *     Status mapping:
         *
         *     - 200 — write succeeded; body is ``{path, size, sha256}``.
         *     - 400 — sandbox violation (absolute, ``..``, NUL in path, symlink
         *       escape).
         *     - 404 — unknown run.
         *     - 409 — run not paused / no review_path / path mismatch /
         *       missing intermediate directory.
         *     - 413 — body exceeds ``MAX_FILE_BYTES``.
         *     - 415 — body is not valid JSON, ``content`` is not a string, the
         *       ``editor`` field is not a string, or the content carries a NUL
         *       byte (binary).
         */
        put: operations["put_artifact_api_runs__run_id__artifacts__file_path__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Defaults
         * @description Return the run-option defaults the dashboard prefills.
         *
         *     Surfaces ``Settings.max_iters`` and ``Settings.iter_timeout`` so the
         *     New Run wizard can render concrete numbers in the form fields rather
         *     than an opaque "server default" placeholder. The values are
         *     process-wide; an in-flight request reads the same instance as
         *     :class:`RelayCore` would inject into a run.
         */
        get: operations["defaults_api_system_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse */
        get: operations["browse_api_system_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BrowseOut */
        BrowseOut: {
            /** Path */
            path: string;
            /** Parent */
            parent: string | null;
            /** Entries */
            entries: components["schemas"]["DirEntry"][];
        };
        /** DirEntry */
        DirEntry: {
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Iter Id */
            iter_id: number | null;
            /** Seq */
            seq: number;
            /** Ts */
            ts: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IterOut */
        IterOut: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /** Phase */
            phase: string | null;
            /** Pi Session Id */
            pi_session_id: string | null;
            /** Prompt */
            prompt: string;
            /** Preamble */
            preamble: string;
            /** Signal Kind */
            signal_kind: string | null;
            /** Signal Args */
            signal_args: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Exit Reason */
            exit_reason: string | null;
        };
        /** PaginatedEventsOut */
        PaginatedEventsOut: {
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** After Seq */
            after_seq: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Preamble */
            preamble: string;
            /** Body */
            body: string;
            /** Prompt */
            prompt: string;
            /** Run Dir */
            run_dir: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Root Path */
            root_path: string;
            /** Name */
            name: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: number;
            /** Root Path */
            root_path: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /** User Id */
            user_id: number;
        };
        /** PromptCreate */
        PromptCreate: {
            /** Project Id */
            project_id?: number | null;
            /** Name */
            name: string;
            /** Body */
            body: string;
        };
        /** PromptOut */
        PromptOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number | null;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /** Body */
            body: string;
            /** Created At */
            created_at: string;
            /** User Id */
            user_id: number;
        };
        /** PromptUpdate */
        PromptUpdate: {
            /** Body */
            body: string;
        };
        /** PromptVersionsOut */
        PromptVersionsOut: {
            /** Versions */
            versions: components["schemas"]["PromptOut"][];
        };
        /** RunCreate */
        RunCreate: {
            /** Project Id */
            project_id: number;
            /** Prompt Body */
            prompt_body?: string | null;
            /** Prompt Id */
            prompt_id?: number | null;
            /** Max Iters */
            max_iters?: number | null;
            /** Iter Timeout */
            iter_timeout?: number | null;
        };
        /** RunDetailOut */
        RunDetailOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: number;
            /** Prompt Id */
            prompt_id: number | null;
            /** Prompt Body */
            prompt_body: string;
            /** User Id */
            user_id: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Max Iters */
            max_iters: number;
            /** Iter Timeout */
            iter_timeout: number;
            /** Worktree Path */
            worktree_path: string | null;
            /** Branch */
            branch: string | null;
            /** Parent Run Id */
            parent_run_id: string | null;
            /** Iters */
            iters?: components["schemas"]["IterOut"][];
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: number;
            /** Prompt Id */
            prompt_id: number | null;
            /** Prompt Body */
            prompt_body: string;
            /** User Id */
            user_id: number;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Max Iters */
            max_iters: number;
            /** Iter Timeout */
            iter_timeout: number;
            /** Worktree Path */
            worktree_path: string | null;
            /** Branch */
            branch: string | null;
            /** Parent Run Id */
            parent_run_id: string | null;
        };
        /** RunResume */
        RunResume: {
            /** Answer */
            answer: string;
        };
        /**
         * SettingsDefaultsOut
         * @description Server-side defaults the dashboard uses to prefill the New Run form.
         */
        SettingsDefaultsOut: {
            /** Max Iters */
            max_iters: number;
            /** Iter Timeout */
            iter_timeout: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                project_id?: number | null;
                status?: string | null;
                limit?: number;
                offset?: number;
                include_children?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_run_children_api_runs__run_id__children_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunResume"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                after_seq?: number;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEventsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_run_api_runs__run_id__preview_get: {
        parameters: {
            query?: {
                prompt_body?: string | null;
                prompt_id?: number | null;
                phase?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompts_api_prompts_get: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_prompt_api_prompts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prompt_api_prompts__prompt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_prompt_api_prompts__prompt_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_prompt_api_prompts__prompt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompt_versions_api_prompts__prompt_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_projects__project_id__files_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_projects__project_id__files__file_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_events__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_runs__run_id__artifacts_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_runs__run_id__artifacts__file_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_artifact_api_runs__run_id__artifacts__file_path__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    defaults_api_system_defaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsDefaultsOut"];
                };
            };
        };
    };
    browse_api_system_browse_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
